### ISSUE TITLE
AR Explanations issues with one norm and infinity norm

### ISSUE THREAD

**Issue by divyat09** [amirhk/mace#4]
I tried to execute method AR on adult dataset with one norm/infinity norm using the command:

 python batchTest.py -d credit -m lr -n infty_norm -a AR -b 0 -s 1
 
It resulted in the following error:

Generating explanation for      batch #0        sample #1/1     (sample index 17148): Traceback (most recent call last):
  File "batchTest.py", line 346, in <module>
    args.process_id)
  File "batchTest.py", line 243, in runExperiments
    standard_deviations, # used solely for feature_tweaking method
  File "batchTest.py", line 122, in generateExplanations
    dataset_obj
  File "/home/t-dimaha/Mace/mace/generateARExplanations.py", line 75, in genExp
    mip_cost_type=mip_cost_type
  File "/home/t-dimaha/Mace/mace/mace_envs_2/lib/python3.7/site-packages/recourse/builder.py", line 632, in __init__
    super().__init__(action_set = action_set, x = x, **kwargs)
  File "/home/t-dimaha/Mace/mace/mace_envs_2/lib/python3.7/site-packages/recourse/builder.py", line 87, in __init__
    self.x = x
  File "/home/t-dimaha/Mace/mace/mace_envs_2/lib/python3.7/site-packages/recourse/builder.py", line 180, in x
    assert len(x) == self.n_variables
AssertionError

The same issue occurs across different datasets, which seems to arise from the 'mip_cost_type' parameter value in the call to recourse.builder.RecourseBuilder().

**Comment by amirhk** [comment]
Is this reproducible at the specific commit from the recourse repo? `9387e6c @ https://github.com/ustunb/actionable-recourse`

**Comment by divyat09** [comment]
Yes, so I cloned the AR repository and shifted the HEAD to the commit 9387e6c4022cc5abbef4a1c2ae150ed0e4da97c1
Installation from this specific commit leads to another issue that I cannot use RecourseBuilder

>>> import recourse
>>> from recourse.builder import RecourseBuilder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/t-dimaha/Mace/mace/mace_envs/lib/python3.7/site-packages/Recourse-0.1-py3.7.egg/recourse/builder.py", line 8, in <module>
    from recourse.defaults import *
  File "/home/t-dimaha/Mace/mace/mace_envs/lib/python3.7/site-packages/Recourse-0.1-py3.7.egg/recourse/defaults.py", line 45, in <module>
    DEFAULT_SOLVER = set_default_solver()
  File "/home/t-dimaha/Mace/mace/mace_envs/lib/python3.7/site-packages/Recourse-0.1-py3.7.egg/recourse/defaults.py", line 17, in set_default_solver
    raise ModuleNotFoundError('could not find installed MIP solver')
ModuleNotFoundError: could not find installed MIP solver

**Comment by divyat09** [comment]
Hi Amir, thanks for your reply. I think there is the above-mentioned issue with using the specific AR version, but I am not sure as it could be some fault from my side. 

I won't need AR method results for now and the MACE method works fine without any issues. Closing for now.
